# Generated by Django 6.0.6 on 2026-07-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(default=True)),
                ('product_name', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=256)),
                ('product_type', models.CharField(choices=[('electronics', 'electronics'), ('garments', 'Garments'), ('Food', 'Food'), ('Baby Toys', 'Baby Toys'), ('other', 'other')], default='electronics', max_length=30)),
                ('In_stock', models.BooleanField(default=True)),
            ],
        ),
    ]
