# Generated by Django 6.0.6 on 2026-07-02 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productmodel',
            new_name='product',
        ),
    ]
