# Generated by Django 6.0.6 on 2026-07-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_productmodel_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='In_stock',
            new_name='in_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.TextField(choices=[('electronics', 'electronics'), ('garments', 'Garments'), ('Food', 'Food'), ('Baby Toys', 'Baby Toys'), ('other', 'other')], default='electronics', max_length=256),
        ),
    ]
